version: '3'

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1

volumes:
  mysql-data:
  seq-data:

services:
  MQ:
    image: rabbitmq:3-management
    container_name: family_budget_develop_rabbitmq
    restart: unless-stopped
    ports:
      - "5671:5672"
      - "15671:15672"
    networks:
      vpcbr:
        ipv4_address: 10.5.1.5
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
  
  db:
    image: mysql
    container_name: family_budget_develop_mysql
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=family_budget
      - MYSQL_USER=family_budget
      - MYSQL_PASSWORD=p-7{a>YX
      - TZ=UTC
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  logs:
    image: datalust/seq:latest
    container_name: family_budget_develop_seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
    volumes:
      - seq-data:/data