### Register 
POST {{apiUrl}}/users/register
Content-Type: application/json

{
  "email": "family.budget.2023@gmail.com",
  "firstName": "Family",
  "lastName": "Budget",
  "username": "family.budget",
  "password": "PH44szAV"
}

### Register
POST {{apiUrl}}/users/register
Content-Type: application/json

{
  "email": "user@example.com",
  "firstName": "firstName",
  "lastName": "lastName",
  "username": "username",
  "password": "password"
}

### Authenticate
POST {{apiUrl}}/users/authenticate
Content-Type: application/json

{
  "username": "username",
  "password": "password"
}

### Authenticate agrynco
POST {{apiUrl}}/users/authenticate
Content-Type: application/json

{
  "username": "agrynco",
  "password": "PH44szAV"
}

### Authenticate agrynco
POST {{apiUrl}}/users/authenticate
Content-Type: application/json

{
  "username": "test",
  "password": "Qtcq5VwrDf"
}

### Get avatar
GET {{apiUrl}}/users/avatar
Authorization: {{authorization}}